#!/bin/sh

arg=$1;
case $arg in
  "status")
    state=`osascript -e 'tell application "iTunes" to player state as string'`;
    echo "iTunes is currently $state.";
    if [ $state = "playing" ]; then
      artist=`osascript -e 'tell application "iTunes" to artist of current track as string'`;
      track=`osascript -e 'tell application "iTunes" to name of current track as string'`;
      echo "Current track $artist:  $track";
    fi
    break ;;

  "play" | "pause" | "stop")
    osascript -e "tell application \"iTunes\" to $arg";
    break ;;

  "next")
    osascript -e 'tell application "iTunes" to next track';
    break ;;

  "prev")
    osascript -e 'tell application "iTunes" to previous track';
    break ;;

  "help" | * )
    echo "Usage: `basename $0` <option>";
    echo "Options: status, play, pause, stop, next, prev";
    break ;;
esac
