#!/bin/sh

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

if [ -f ~/.zshrc ]; then
  mv ~/.zshrc ~/.zshrc.bak
fi

cp ~/dotfiles/resources/_zshrc ~/.zshrc
echo "Dropped in .zshrc file"

if [ -f ~/.profile ]; then
  mv ~/.profile ~/.profile.bak
fi

cp ~/dotfiles/resources/_profile ~/.profile
echo "Dropped in .profile file"

cp ~/dotfiles/resources/jived*.zsh-theme ~/.oh-my-zsh/custom/themes/
echo "Installed jived oh-my-zsh themes"

OS=$(uname -s)
if [ "$OS" = "Linux" ]; then
  if ps aux | grep [X]org > /dev/null; then
    echo "Installing Lepton Firefox Tab Fixes"
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.sh)"
  fi
fi

if [[ "$OS" = "Darwin" ]]; then
  echo "Installing Fonts"
  brew install font-meslo-lg-nerd-font

  echo "Installing Jived terminal theme"
  open ~/dotfiles/resources/Jived.terminal

  echo "Setting up iTerm2"
  defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/resources/"
  defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

  echo "macOS Specific Config"
  defaults write -g ApplePressAndHoldEnabled -bool false

  echo "Installing Lepton Firefox Tab Fixes"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/master/install.sh)"
fi

echo "Setting up vim"
echo "runtime vimrc" > ~/.vimrc
mkdir -p ~/.vim/bundle/
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
ln -s ~/dotfiles/vimrc ~/.vim/vimrc
vim +PluginInstall
